"""empty message

Revision ID: 0272dfae222c
Revises: 
Create Date: 2025-04-24 21:19:02.062469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0272dfae222c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadstreamers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_only_self', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploadstreamers', schema=None) as batch_op:
        batch_op.drop_column('is_only_self')

    # ### end Alembic commands ###
